### ISSUE TITLE
unable to open file (in project "MoneyFlow")

### ISSUE THREAD

**Issue by urakalee** [prof18/MoneyFlow#19]
can not run in Xcode 13.2.1

MoneyFlow/iosApp/Assets/Config.xcconfig:1:1: unable to open file (in project "MoneyFlow")

**Comment by prof18** [comment]
My bad, I haven't updated the README accordingly. 

That file is for storing the API keys of the Dropbox SDK. 
You can use this template to create your file: [Config.xcconfig.template](https://github.com/prof18/MoneyFlow/blob/main/iosApp/Assets/Config.xcconfig.template)

**Comment by prof18** [comment]
Now the README is updated with the required info.
https://github.com/prof18/MoneyFlow#how-to-build
